spring:
  application:
    name: user-management-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/assessment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
  
# Security Configuration
security:
  jwt:
    secret: your-secret-key-should-be-very-secure-and-not-shared-publicly
    expiration: 86400000  # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    com.assessment: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 